name: Lint
run-name: Run Linting on ${{github.ref_name}}

on:
  workflow_dispatch:

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run Formatter
        run: pnpm format

      - name: Check for changes
        id: git-check
        run: |
          result=$(git diff-index --quiet HEAD || echo "Changes found")
          echo "::set-output name=result::$result"

      - name: Commit and Push changes
        if: steps.git-check.outputs.result == 'Changes found'
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
